name = "COD Order App"
client_id = "YOUR_CLIENT_ID"
application_url = "YOUR_APP_URL"
embedded = true

[access_scopes]
# Required for creating orders
scopes = "write_orders,write_products,read_products"

[auth]
redirect_urls = ["YOUR_APP_URL/auth/callback"]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false