name = "COD Order App"
client_id = "765137b68ca7f605992d521c39116e5a"
application_url = "9cd7790357cd6e033168b3bf292645d7"
embedded = true

[access_scopes]
# Required for creating orders
scopes = "write_orders,write_products,read_products"

[auth]
redirect_urls = ["https://codnns.netlify.app/auth/callback"]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
